# Generated by Django 5.1.1 on 2024-11-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feriado_alter_evento_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Feriado',
        ),
    ]
