# Generated by Django 5.1.1 on 2024-11-25 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feriado_alter_evento_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriado',
            name='region',
        ),
    ]
