# Generated by Django 5.1.1 on 2024-11-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_feriado_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
