# Generated by Django 5.1.1 on 2024-11-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feriado_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriado',
            name='region',
        ),
    ]
